fun main() {

    println("hello world")
    println("dashboard")
    println("welcome to android developer full course through jetpack compose")
    println("I want to very excited to learn android programming kotlin")
    println("our next topic is variable and we wil start soon")
    println("dashboard")
    println("menu")
    println("additional information")
    println("settings")
    println("report")
    println("crypto wallet")
    println("buy/sell ico")
    println("enter your unique id")
    println("enter your private key")
    println("enter your private key")
    println("play in metaverse")
    println("exchange")
    println("enter amount you want to send")
    println("live course")
    println("home")
    println("login")
    println("enter forget password")
    println("enter cart")
    println("enter your phone number")
    println("enter subject")
}